const alcohol = [
    {
    _id: '1',
    name: 'Grey Goose Vodka',
    description: 'A vodka from Russia? Enjoy.',
    brand: 'Grey Goose',
    category: 'Liquor',
    price: 79.99,
    countInStock: 3,
    rating: 5,
    numReviews: 3,
},
{
    _id: '2',
    name: 'Black Label',
    description: 'The expensive stuff. Time to get lit',
    brand: 'Johnnie Walker',
    category: 'Liquor',
    price: 149.99,
    countInStock: 15,
    rating: 5,
    numReviews: 2,
},
{
    _id: '3',
    name: 'Fireball',
    description: 'For the hipsters out of Brooklyn. Enjoy.',
    brand: 'Fireball',
    category: 'Liquor',
    price: 19.99,
    countInStock: 17,
    rating: 4,
    numReviews: 7,
},
]